### PR TITLE
[TASK] Provide basic XLIFF files

### LINKED ISSUE #20: Provide missing XLIFF files
On a fresh install (version ~2 and Neos 2) an Exception 

```
#1334759591: No XLIFF file is available for MOC.Varnish::Main::en in the locale chain.
```

is thrown.

### PR DESCRIPTION
**Pull request by johannessteu**
Provide basic XLIFF files to prevent an `No XLIFF file is available for MOC.Varnish::Main::en in the locale chain` Exception

Fixes #20

### CODE REVIEW

**Comment by hlubek** [comment]
Hi Johannes,

thx for the PR. I think we need to solve this issue in the Neos core. It should not be necessary that every 3rd party package has translations for the user locale or the system will throw exceptions.

So we can merge this anyway but there's a problem in the way Neos deals with localization right now that should be solved.

**Comment by skurfuerst** [comment]
Full ack! We should solve this in Neos core...

**Comment by kitsunet** [comment]
I guess we need check before doing the glob in the \TYPO3\Neos\Service\XliffService::getCachedJson() line 105

**Comment by johannessteu** [comment]
Is there already an issue on jira regarding this topic? If not i'll create an issue and try to patch it later this evening.
A merge would be nice since the package is not working with the current state. I'll create another PR as soon as the core is patched. Are you ok with that?

**Comment by hlubek** [comment]
Okay for me, doesn't hurt for now.

**Pull request merged**
