### PR TITLE
TASK: Migrate "typoScriptPath" to "fusionPath"

### PR DESCRIPTION
**Pull request by aertmann**
Needed since Neos 3.0.4

Resolves #34

### CODE REVIEW

**Comment by kdambekalns** [comment]
Actually #34 was already a PR… ;)

**Comment by peterbucher** [comment]
@aertmann 
Affects Neos versions since 3.1.2 and 3.0.4, according to @kdambekalns

**Comment by aertmann** [comment]
Whoops didn't even notice that lol, sorry about that @peterbucher

**Comment by aertmann** [comment]
Dupe of #34

**Pull request closed without merging**
